const asyncHandler = (requestHandler) => {
    (req, res, next) => {
        Promise.resolve(requestHandler(req, res, next))
        .catch((err) => next(err))
    }
}

import { json } from "body-parser"
import { message } from "statuses"

export {asyncHandler}

// const asyncHandler = () => {}
// const asyncHandler = (func) => async () => {}

// below code is of try catch example  
// const asyncHandler = (fn) => async (req, res, next) => {
//     try {
//         await fn(req, res, next)
//     } catch (error) {
//         res.status(err.code || 500).json({
//             success: false,
//             message: err.message
//         })
//     }
// }